### ISSUE TITLE
3rd party assets + diffs

### ISSUE THREAD

**Issue by jdetter** [boppygames/Community-Game#26]
## Todo

 - [x] 3rd party assets need to be able to be patched after downloading
 - [x] If asset has not been patched, don't allow user to enter playmode
 - [x] New script: `create-patch.sh <file or directory> ...`
   - [x] List all changed files or directories
   - [x] Tell user to then reimport files from package, back to the original state
   - [x] Take diffs of all files, compare old files vs new files (modified, to original)
   - [ ] Save sha256 of original and modified files
   - [ ] Repatch the files
   - [x] Save the patch file in the `Patches/` directory
